variables:
  # docker registery in gitlab
  LOCAL_REGISTRY_HOSTNAME: "registry.snapp.tech"
  LOCAL_REGISTRY_USER: "gitlab-ci-token"
  LOCAL_REGISTRY_TOKEN: "$CI_JOB_TOKEN"
  REGISTRY_MIRROR: "https://mirror.snappcloud.io"

  # please consider the following link for gitlab ci/cd variables
  # https://docs.gitlab.com/ee/ci/variables/

before_script:
  # Prepare required calculated variables
  - export CI_COMMIT_SHORT_SHA=$(echo $CI_COMMIT_SHA | head -c 8)
  - export LOCAL_IMAGE_PATH="$LOCAL_REGISTRY_HOSTNAME/$CI_PROJECT_PATH"
  - alias docker-run='docker run --rm "$LOCAL_IMAGE_PATH:$CI_COMMIT_SHORT_SHA-build"'

stages:
  - lint-test
  - docker-build

lint:
  image: golangci/golangci-lint:latest
  stage: lint-test
  variables:
    GOPROXY: http://172.16.77.197:3000
    GOOS: 'linux'
    GOARCH: 'amd64'
  script:
    - go mod download
    - golangci-lint run --enable-all

test:
  image: golang:latest
  stage: lint-test
  variables:
    GOPROXY: http://172.16.77.197:3000
  script:
    - mv .ci/config.ci.yml config.yml
    - mv .ci/shards.ci.yml shards.yml
    - go test ./...
  coverage: '/^total:\t+\(statements\)\t+(\d+\.\d+)%/'
  services:
    - name: tile38/tile38
      alias: tile38_1
    - name: tile38/tile38
      alias: tile38_2

build:docker:
  stage: docker-build
  image: docker:git
  variables:
    PROXY: "http://default:UKDxQ2MXU38Q3JYwP4AfAMy8Ajn6Ze8H@mirror.snappcloud.io:30128"
  services:
    - name: docker:dind
      command: ["--registry-mirror=$REGISTRY_MIRROR"]
  script:
    - docker login -u $LOCAL_REGISTRY_USER -p $LOCAL_REGISTRY_TOKEN $LOCAL_REGISTRY_HOSTNAME
    - docker pull $LOCAL_IMAGE_PATH:build-cache || true
    - docker pull $LOCAL_IMAGE_PATH:build-cache-$CI_COMMIT_REF_SLUG || true
    - docker pull $LOCAL_IMAGE_PATH:release-cache || true
    - >
      docker build \
        --target build \
        --cache-from $LOCAL_IMAGE_PATH:build-cache \
        --build-arg http_proxy=$PROXY \
        --build-arg https_proxy=$PROXY \
        --tag $LOCAL_IMAGE_PATH:build-cache \
        --tag $LOCAL_IMAGE_PATH:build-cache-$CI_COMMIT_REF_SLUG \
        --tag $LOCAL_IMAGE_PATH:$CI_COMMIT_SHORT_SHA-build \
        ./
    - >
      docker build \
        --cache-from $LOCAL_IMAGE_PATH:build-cache \
        --cache-from $LOCAL_IMAGE_PATH:latest-cache \
        --build-arg http_proxy=$PROXY \
        --build-arg https_proxy=$PROXY \
        --tag $LOCAL_IMAGE_PATH:release-cache \
        --tag $LOCAL_IMAGE_PATH:$CI_COMMIT_SHORT_SHA-release \
        ./
    - docker push $LOCAL_IMAGE_PATH:$CI_COMMIT_SHORT_SHA-release
    - docker push $LOCAL_IMAGE_PATH:build-cache
    - docker push $LOCAL_IMAGE_PATH:build-cache-$CI_COMMIT_REF_SLUG
    - docker push $LOCAL_IMAGE_PATH:release-cache
